export const S = {
  app: { background: "#0d0f11", minHeight: "100vh", maxWidth: 480, margin: "0 auto", fontFamily: "'Inter',system-ui,sans-serif", color: "#e5e7eb", display: "flex", flexDirection: "column", height: "100vh" },
  loadWrap: { display: "flex", alignItems: "center", justifyContent: "center", height: "100vh", background: "#0d0f11" },
  header: { padding: "14px 14px 10px", borderBottom: "1px solid #1c2127", flexShrink: 0 },
  logo: { fontSize: 17, fontWeight: 800, color: "#4ade80", letterSpacing: "-0.04em" },
  dateLabel: { fontSize: 10, color: "#6b7280", textTransform: "capitalize", marginTop: 1 },
  body: { padding: "12px 12px 84px", overflowY: "auto", flex: 1, WebkitOverflowScrolling: "touch" },
  tabBar: { position: "fixed", bottom: 0, left: 0, right: 0, maxWidth: 480, margin: "0 auto", display: "flex", justifyContent: "space-around", background: "#0f1115", borderTop: "1px solid #1c2127", padding: "4px 0 6px", zIndex: 100, flexShrink: 0 },
  tabBtn: { background: "none", border: "none", display: "flex", flexDirection: "column", alignItems: "center", padding: "3px 6px", cursor: "pointer", fontFamily: "inherit" },
  card: { background: "#141719", border: "1px solid #222830", borderRadius: 9, padding: "12px 13px", marginBottom: 8 },
  lbl: { fontSize: 9, color: "#7a8290", marginBottom: 4, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.07em" },
  title: { fontSize: 15, fontWeight: 700, color: "#e5e7eb", marginBottom: 12, letterSpacing: "-0.02em" },
  inp: { width: "100%", background: "#1a1d21", border: "1px solid #252a30", borderRadius: 5, padding: "7px 9px", fontSize: 12, color: "#e5e7eb", outline: "none", fontFamily: "inherit", boxSizing: "border-box" },
  ta: { width: "100%", background: "#1a1d21", border: "1px solid #252a30", borderRadius: 5, padding: "7px 9px", fontSize: 11, color: "#e5e7eb", outline: "none", resize: "vertical", fontFamily: "inherit", boxSizing: "border-box" },
  chip: { padding: "4px 10px", borderRadius: 5, fontSize: 10, cursor: "pointer", fontWeight: 500, fontFamily: "inherit", border: "1px solid" },
  g2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6, marginBottom: 10 },
  mini: { background: "#141719", border: "1px solid #222830", borderRadius: 8, padding: "8px 10px", textAlign: "center" },
  habBtn: { display: "flex", alignItems: "center", gap: 8, width: "100%", padding: "9px 10px", borderRadius: 7, border: "1px solid", marginBottom: 4, cursor: "pointer", background: "none", textAlign: "left", fontFamily: "inherit" },
  chk: { width: 20, height: 20, borderRadius: 5, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 700, flexShrink: 0 },
  navC: { display: "flex", alignItems: "center", gap: 12, width: "100%", padding: "12px 14px", background: "#141719", border: "1px solid #222830", borderRadius: 9, marginBottom: 6, cursor: "pointer", fontFamily: "inherit", textAlign: "left" },
  back: { background: "none", border: "none", color: "#4ade80", fontSize: 12, cursor: "pointer", marginBottom: 12, padding: 0, fontFamily: "inherit", fontWeight: 500 },
  pBtn: { padding: "9px 20px", borderRadius: 7, fontSize: 12, fontWeight: 600, background: "#4ade80", border: "none", color: "#0d0f11", cursor: "pointer", fontFamily: "inherit", marginBottom: 10 },
  smBtn: { padding: "4px 10px", borderRadius: 5, fontSize: 10, fontWeight: 500, background: "transparent", border: "1px solid #252a30", color: "#4ade80", cursor: "pointer", fontFamily: "inherit" },
  delBtn: { background: "none", border: "none", color: "#ef4444", fontSize: 16, cursor: "pointer", padding: "0 3px" },
  subT: { flex: 1, padding: "6px 0", borderRadius: 5, fontSize: 11, fontWeight: 500, cursor: "pointer", border: "1px solid", fontFamily: "inherit", textAlign: "center" },
  evRow: { display: "flex", gap: 8, alignItems: "center", padding: "5px 0", borderBottom: "1px solid #1c2127" },
  evCard: { padding: "10px 12px", background: "#141719", border: "1px solid #222830", borderRadius: 8, marginBottom: 5 },
  muted: { fontSize: 11, color: "#6b7280", margin: 0 },
};
